export enum EventKey {
    BET_BULL_15 = "BET_BULL_15",
    BET_BEAR_15 = "BET_BEAR_15",
    START_ROUND_15= "START_ROUND_15",
    REFERRAL_BONUS_15 = "REFERRAL_BONUS_15",
    BET_BULL_30 = "BET_BULL_30",
    BET_BEAR_30 = "BET_BEAR_30",
    START_ROUND_30= "START_ROUND_30",
    REFERRAL_BONUS_30 = "REFERRAL_BONUS_30"
}
